/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intelaf.view;

import com.intelaf.controller.MainControl;
import com.intelaf.model.Cliente;

/**
 *
 * @author cesar31
 */
public class ClienteView extends javax.swing.JFrame {

    private TiendasClienteView tiendaCliente;
    private PedidosClienteView pedidosCl;
    private MainControl control;
    private Cliente cliente;
    
    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
    }
    
    public void initializeControl(MainControl control, Cliente cliente) {
        this.control = control;
        this.cliente = cliente;
        initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        tiendasButton = new javax.swing.JButton();
        misPedidosButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        navPanel.setBackground(new java.awt.Color(248, 147, 31));
        navPanel.setMinimumSize(new java.awt.Dimension(100, 70));
        navPanel.setPreferredSize(new java.awt.Dimension(700, 70));

        tiendasButton.setBackground(new java.awt.Color(0, 0, 0));
        tiendasButton.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        tiendasButton.setForeground(new java.awt.Color(248, 147, 31));
        tiendasButton.setText("Tiendas");
        tiendasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiendasButtonActionPerformed(evt);
            }
        });

        misPedidosButton.setBackground(new java.awt.Color(0, 0, 0));
        misPedidosButton.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        misPedidosButton.setForeground(new java.awt.Color(248, 147, 31));
        misPedidosButton.setText("Mis Pedidos");
        misPedidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misPedidosButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(248, 147, 31));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tiendasButton)
                .addGap(18, 18, 18)
                .addComponent(misPedidosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiendasButton)
                    .addComponent(misPedidosButton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        mainPanel.setBackground(new java.awt.Color(248, 147, 31));
        mainPanel.setPreferredSize(new java.awt.Dimension(688, 618));
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        control.cerrarSesionCliente();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tiendasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiendasButtonActionPerformed
        // TODO add your handling code here:
        initView();
    }//GEN-LAST:event_tiendasButtonActionPerformed

    private void initView() {
        tiendaCliente = new TiendasClienteView();
        tiendaCliente.initializeComponents(control, cliente);
        this.mainPanel.setVisible(false);
        this.mainPanel.removeAll();
        this.mainPanel.add(tiendaCliente);
        this.mainPanel.setVisible(true);
    }
    
    private void misPedidosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misPedidosButtonActionPerformed
        // TODO add your handling code here:
        pedidosCl = new PedidosClienteView();
        pedidosCl.initializeComponents(control, cliente);
        this.mainPanel.setVisible(false);
        this.mainPanel.removeAll();
        this.mainPanel.add(pedidosCl);
        this.mainPanel.setVisible(true);
    }//GEN-LAST:event_misPedidosButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton misPedidosButton;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton tiendasButton;
    // End of variables declaration//GEN-END:variables
}
