
package com.intelaf.view;

import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author cesar31
 */
public class Login extends javax.swing.JFrame {

    List<String> tiendas;
    
    /**
     * Creates new form Login
     * @param tiendas
     */
    public Login(List<String> tiendas) {
        this.tiendas = tiendas;
        initComponents();
        this.setLocationRelativeTo(null);
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        iniciarButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        codigoLabel = new javax.swing.JLabel();
        usuarioRadio = new javax.swing.JRadioButton();
        tiendasCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 147, 31));
        setMinimumSize(new java.awt.Dimension(400, 650));
        setPreferredSize(new java.awt.Dimension(400, 650));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(248, 147, 31));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(400, 700));

        logoLabel.setBackground(new java.awt.Color(248, 147, 31));
        logoLabel.setMaximumSize(new java.awt.Dimension(300, 300));
        logoLabel.setMinimumSize(new java.awt.Dimension(300, 300));
        logoLabel.setOpaque(true);
        logoLabel.setPreferredSize(new java.awt.Dimension(300, 300));

        codigoText.setBackground(new java.awt.Color(255, 255, 255));
        codigoText.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        codigoText.setForeground(new java.awt.Color(0, 0, 0));
        codigoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        codigoText.setMargin(new java.awt.Insets(5, 10, 2, 6));
        codigoText.setMinimumSize(new java.awt.Dimension(250, 40));
        codigoText.setPreferredSize(new java.awt.Dimension(250, 40));

        iniciarButton.setBackground(new java.awt.Color(0, 0, 0));
        iniciarButton.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        iniciarButton.setForeground(new java.awt.Color(248, 147, 31));
        iniciarButton.setText("Iniciar Sesión");
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });

        separator.setBackground(new java.awt.Color(0, 0, 0));
        separator.setMinimumSize(new java.awt.Dimension(300, 10));
        separator.setPreferredSize(new java.awt.Dimension(300, 10));

        codigoLabel.setBackground(new java.awt.Color(248, 147, 31));
        codigoLabel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        codigoLabel.setForeground(new java.awt.Color(255, 255, 255));
        codigoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoLabel.setText("Codigo");
        codigoLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        codigoLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        codigoLabel.setRequestFocusEnabled(false);

        usuarioRadio.setBackground(new java.awt.Color(248, 147, 31));
        usuarioRadio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        usuarioRadio.setForeground(new java.awt.Color(255, 255, 255));
        usuarioRadio.setText("Empleado");

        tiendasCombo.setBackground(new java.awt.Color(248, 147, 31));
        tiendasCombo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tiendasCombo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(usuarioRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tiendasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(iniciarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiendasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(iniciarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoText;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSeparator separator;
    private javax.swing.JComboBox<String> tiendasCombo;
    private javax.swing.JRadioButton usuarioRadio;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        ImageIcon image = new ImageIcon(getClass().getResource("/images/empresa.png"));
        this.logoLabel.setIcon(new ImageIcon(image.getImage().getScaledInstance(logoLabel.getPreferredSize().width, logoLabel.getPreferredSize().width, Image.SCALE_SMOOTH)));
        tiendas.forEach((t) -> {
            tiendasCombo.addItem(t);
        });
    }
}
