
package com.intelaf.view;

import com.intelaf.controller.MainControl;
import com.intelaf.model.Producto;

/**
 *
 * @author cesar31
 */
public class ProductoForModal extends javax.swing.JPanel {

    private MainControl control;
    private Producto producto;
    private boolean isEdit;
    
    /**
     * Creates new form createCliente
     */
    public ProductoForModal() {
        initComponents();
        isEdit = false;
    }
    
    public void initializeControl(MainControl control) {
        this.control = control;
    }
    
    public void initializeProducto(Producto producto) {
        this.producto = producto;
        isEdit = true;
        setDatos();
    }
        
    private void setDatos() {
        if(isEdit) {
            codigoText.setEditable(false);
        }else {
            codigoText.setEditable(true);
        }
        
        if(producto != null) {
            codigoText.setText(producto.getCodigoProductos());
            nombreText.setText(producto.getNombre());
            fabricanteText.setText(producto.getFabricante());
            precioText.setText(String.valueOf(producto.getPrecio()));
            garantiaText.setText(String.valueOf(producto.getGarantia()));
            descriptionText.setText(producto.getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionLabel = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        fabricanteLabel = new javax.swing.JLabel();
        fabricanteText = new javax.swing.JTextField();
        descripcionLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        precioText = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        garantiaLabel = new javax.swing.JLabel();
        garantiaText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(248, 147, 31));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));

        informacionLabel.setBackground(new java.awt.Color(248, 147, 31));
        informacionLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        informacionLabel.setForeground(new java.awt.Color(0, 0, 0));
        informacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informacionLabel.setText("Informacion del Cliente");
        informacionLabel.setToolTipText("");
        informacionLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        informacionLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        informacionLabel.setPreferredSize(new java.awt.Dimension(300, 30));

        codigoLabel.setBackground(new java.awt.Color(248, 147, 31));
        codigoLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        codigoLabel.setForeground(new java.awt.Color(0, 0, 0));
        codigoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigoLabel.setText("Codigo");
        codigoLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        codigoLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        codigoLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        codigoText.setBackground(new java.awt.Color(255, 255, 255));
        codigoText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        codigoText.setForeground(new java.awt.Color(0, 0, 0));
        codigoText.setMinimumSize(new java.awt.Dimension(150, 30));
        codigoText.setPreferredSize(new java.awt.Dimension(150, 30));
        codigoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoTextKeyTyped(evt);
            }
        });

        nombreLabel.setBackground(new java.awt.Color(248, 147, 31));
        nombreLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreLabel.setText("Nombre");
        nombreLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        nombreLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        nombreLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        nombreText.setBackground(new java.awt.Color(255, 255, 255));
        nombreText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nombreText.setForeground(new java.awt.Color(0, 0, 0));
        nombreText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombreText.setMinimumSize(new java.awt.Dimension(402, 30));
        nombreText.setPreferredSize(new java.awt.Dimension(402, 30));

        fabricanteLabel.setBackground(new java.awt.Color(248, 147, 31));
        fabricanteLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        fabricanteLabel.setForeground(new java.awt.Color(0, 0, 0));
        fabricanteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fabricanteLabel.setText("Fabricante");
        fabricanteLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        fabricanteLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        fabricanteLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        fabricanteText.setBackground(new java.awt.Color(255, 255, 255));
        fabricanteText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        fabricanteText.setForeground(new java.awt.Color(0, 0, 0));
        fabricanteText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fabricanteText.setMinimumSize(new java.awt.Dimension(402, 30));
        fabricanteText.setPreferredSize(new java.awt.Dimension(402, 30));

        descripcionLabel.setBackground(new java.awt.Color(248, 147, 31));
        descripcionLabel.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        descripcionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descripcionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descripcionLabel.setText("Descripcion");
        descripcionLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        descripcionLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        descripcionLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        precioLabel.setBackground(new java.awt.Color(248, 147, 31));
        precioLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        precioLabel.setForeground(new java.awt.Color(0, 0, 0));
        precioLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioLabel.setText("Precio");
        precioLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        precioLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        precioLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        precioText.setBackground(new java.awt.Color(255, 255, 255));
        precioText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        precioText.setForeground(new java.awt.Color(0, 0, 0));
        precioText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        precioText.setMinimumSize(new java.awt.Dimension(150, 30));
        precioText.setPreferredSize(new java.awt.Dimension(150, 30));

        aceptarButton.setBackground(new java.awt.Color(0, 0, 0));
        aceptarButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        aceptarButton.setForeground(new java.awt.Color(248, 147, 31));
        aceptarButton.setText("Aceptar");
        aceptarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 117, 12)));
        aceptarButton.setMinimumSize(new java.awt.Dimension(125, 32));
        aceptarButton.setPreferredSize(new java.awt.Dimension(125, 32));
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelarButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(248, 147, 31));
        cancelarButton.setText("Cancelar");
        cancelarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 117, 12)));
        cancelarButton.setMinimumSize(new java.awt.Dimension(125, 32));
        cancelarButton.setPreferredSize(new java.awt.Dimension(125, 32));
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        garantiaLabel.setBackground(new java.awt.Color(248, 147, 31));
        garantiaLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        garantiaLabel.setForeground(new java.awt.Color(0, 0, 0));
        garantiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        garantiaLabel.setText("Garantia");
        garantiaLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        garantiaLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        garantiaLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        garantiaText.setBackground(new java.awt.Color(255, 255, 255));
        garantiaText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        garantiaText.setForeground(new java.awt.Color(0, 0, 0));
        garantiaText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        garantiaText.setMinimumSize(new java.awt.Dimension(150, 30));
        garantiaText.setPreferredSize(new java.awt.Dimension(150, 30));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(414, 80));

        descriptionText.setBackground(new java.awt.Color(255, 255, 255));
        descriptionText.setColumns(20);
        descriptionText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        descriptionText.setForeground(new java.awt.Color(0, 0, 0));
        descriptionText.setLineWrap(true);
        descriptionText.setRows(5);
        descriptionText.setPreferredSize(new java.awt.Dimension(414, 80));
        jScrollPane1.setViewportView(descriptionText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(informacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fabricanteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fabricanteText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(garantiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(garantiaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(informacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fabricanteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fabricanteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garantiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garantiaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(descripcionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para verificar la informacion del ciente antes de procesar la venta
     * @param evt 
     */
    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
        String codigo = codigoText.getText();
        String nombre = nombreText.getText();
        String fabricante = fabricanteText.getText();
        String garantiaString = garantiaText.getText();
        String precioString = precioText.getText();
        String description = descriptionText.getText();
        
        if(!codigo.isEmpty() && !nombre.isEmpty() && !fabricante.isEmpty() && !precioString.isEmpty()) {
            double precio = getDouble(precioString);
            if(precio > 0) {
                int garantia = getInteger(garantiaString);
                if(garantia >= 0) {
                    if(isEdit) {
                        producto.setNombre(nombre);
                        producto.setFabricante(fabricante);
                        producto.setPrecio(precio);
                        producto.setGarantia(garantia);
                        producto.setDescripcion(description.isEmpty() ? null : description);
                        
                        control.updateProductos(producto);
                    } else {
                        if(producto == null) {
                            producto = new Producto(nombre, fabricante, codigo, precio, (description.isEmpty() || description.isBlank() ? null : description), garantia);
                            control.insertProduct(producto);
                        } else {
                            control.crearAlerta("Advertencia", "El codigo del producto ingresado ya existe", null);
                            codigoText.setText("");
                        }
                    }
                } else {
                    control.crearAlerta("Error", "El valor que indico para la garantia no es valido", null);
                    garantiaText.setText("");
                }
            }else {
                control.crearAlerta("Error", "El valor que indico para el precio no es valido", null);
                precioText.setText("");
            }
        } else {
            control.crearAlerta("Error", "Debe llenar los campos codigo, nombre, telefono y precio", null);
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed
   
    private double getDouble(String precioString) {
        if(precioString.isEmpty() || precioString.isBlank()) {
            return 0;
        }
        
        try {
            return Double.parseDouble(precioString);
        } catch (NumberFormatException e) {
            return -1;
        }
    }
    
    private int getInteger(String garantiaString) {
        if(garantiaString.isEmpty() || garantiaString.isBlank()) {
            return 0;
        }
        
        try {
            return Integer.parseInt(garantiaString);
        } catch (NumberFormatException e) {
            return -1;
        }        
    }
    
    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        control.closeModal();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void codigoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyReleased
        // TODO add your handling code here:
        String codigo = codigoText.getText();
        if(!codigo.isEmpty() && !codigo.isEmpty()) {
            this.producto = control.getProducto(codigo);
        } else {
            this.producto = null;
        }
    }//GEN-LAST:event_codigoTextKeyReleased

    private void codigoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextKeyPressed

    private void codigoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyTyped
        // TODO add your handling code here:
        if(codigoText.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_codigoTextKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoText;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JLabel fabricanteLabel;
    private javax.swing.JTextField fabricanteText;
    private javax.swing.JLabel garantiaLabel;
    private javax.swing.JTextField garantiaText;
    private javax.swing.JLabel informacionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField precioText;
    // End of variables declaration//GEN-END:variables
}
