
package com.intelaf.view;

import com.intelaf.controller.MainControl;
import com.intelaf.model.*;
import java.util.*;

/**
 *
 * @author cesar31
 */
public class RegistroView extends javax.swing.JPanel {

    private MainControl control;
    private List<Pedido> pedidos;
    private Tienda tienda;
    private String[][] listPedidos;
    private boolean isRegistrar;
    private boolean isHoy;
    
    /**
     * Creates new form VentaView
     */
    public RegistroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        scrollTiendas = new javax.swing.JScrollPane();
        pedidosTable = new javax.swing.JTable();
        sucursalesLabel = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        tipoPedidosCombo = new javax.swing.JComboBox<>();
        hoyRadio = new javax.swing.JRadioButton();
        atrasadosRadio = new javax.swing.JRadioButton();

        radioButtonGroup.add(hoyRadio);
        radioButtonGroup.add(atrasadosRadio);

        setBackground(new java.awt.Color(248, 147, 31));
        setMinimumSize(new java.awt.Dimension(800, 700));

        pedidosTable.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pedidosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        pedidosTable.setEditingColumn(0);
        pedidosTable.setEditingRow(0);
        pedidosTable.setMinimumSize(new java.awt.Dimension(700, 300));
        pedidosTable.setPreferredSize(new java.awt.Dimension(700, 300));
        pedidosTable.setRowHeight(36);
        pedidosTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        pedidosTable.setSelectionForeground(new java.awt.Color(248, 147, 31));
        pedidosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pedidosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollTiendas.setViewportView(pedidosTable);
        pedidosTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        sucursalesLabel.setBackground(new java.awt.Color(248, 147, 31));
        sucursalesLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        sucursalesLabel.setForeground(new java.awt.Color(255, 255, 255));
        sucursalesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sucursalesLabel.setText("Pedidos");
        sucursalesLabel.setMaximumSize(new java.awt.Dimension(150, 36));
        sucursalesLabel.setMinimumSize(new java.awt.Dimension(150, 36));
        sucursalesLabel.setPreferredSize(new java.awt.Dimension(150, 36));

        editarButton.setBackground(new java.awt.Color(0, 0, 0));
        editarButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        editarButton.setForeground(new java.awt.Color(248, 147, 31));
        editarButton.setText("Registrar...");
        editarButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 103, 27), 1, true));
        editarButton.setFocusPainted(false);
        editarButton.setMaximumSize(new java.awt.Dimension(125, 32));
        editarButton.setMinimumSize(new java.awt.Dimension(125, 32));
        editarButton.setPreferredSize(new java.awt.Dimension(125, 32));
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        agregarButton.setBackground(new java.awt.Color(0, 0, 0));
        agregarButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        agregarButton.setForeground(new java.awt.Color(248, 147, 31));
        agregarButton.setText("Agregar...");
        agregarButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 103, 27), 1, true));
        agregarButton.setFocusPainted(false);
        agregarButton.setMaximumSize(new java.awt.Dimension(125, 32));
        agregarButton.setMinimumSize(new java.awt.Dimension(125, 32));
        agregarButton.setPreferredSize(new java.awt.Dimension(125, 32));
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        tipoPedidosCombo.setBackground(new java.awt.Color(0, 0, 0));
        tipoPedidosCombo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tipoPedidosCombo.setForeground(new java.awt.Color(248, 147, 31));
        tipoPedidosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Pedidos", "Entregar Pedidos" }));
        tipoPedidosCombo.setMinimumSize(new java.awt.Dimension(200, 32));
        tipoPedidosCombo.setPreferredSize(new java.awt.Dimension(200, 32));
        tipoPedidosCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoPedidosComboItemStateChanged(evt);
            }
        });

        hoyRadio.setBackground(new java.awt.Color(248, 147, 31));
        hoyRadio.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        hoyRadio.setForeground(new java.awt.Color(0, 0, 0));
        hoyRadio.setSelected(true);
        hoyRadio.setText("Hoy");
        hoyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoyRadioActionPerformed(evt);
            }
        });

        atrasadosRadio.setBackground(new java.awt.Color(248, 147, 31));
        atrasadosRadio.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        atrasadosRadio.setForeground(new java.awt.Color(0, 0, 0));
        atrasadosRadio.setText("Atrasados");
        atrasadosRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasadosRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sucursalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoPedidosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hoyRadio)
                        .addGap(18, 18, 18)
                        .addComponent(atrasadosRadio)
                        .addContainerGap(223, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollTiendas, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sucursalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoPedidosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoyRadio)
                            .addComponent(atrasadosRadio))))
                .addGap(18, 18, 18)
                .addComponent(scrollTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
  
    /**
     * @param control 
     * @param tienda 
     */
    public void initializeComponents(MainControl control, Tienda tienda) {
        this.control = control;
        this.tienda = tienda;
        isRegistrar = true;
        isHoy = true;
        pedidos = new ArrayList<>();
        actualizarDatos();
    }
    
    /**
     * Metodo para editar la informacion de un empleado
     * @param evt 
     */
    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
        int row = pedidosTable.getSelectedRow();
        if(row != -1) {
            Pedido tmp = pedidos.get(row);
            control.initProcesarPedidoModal(tmp, isHoy,true);
        } else {
            control.crearAlerta("Alerta", "Debe seleccionar una tienda para poder editarla", null);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void tipoPedidosComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoPedidosComboItemStateChanged
        // TODO add your handling code here:
        this.isRegistrar = this.tipoPedidosCombo.getSelectedIndex() == 0;
        actualizarDatos();
    }//GEN-LAST:event_tipoPedidosComboItemStateChanged

    private void hoyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoyRadioActionPerformed
        // TODO add your handling code here:
        isHoy = hoyRadio.isSelected();
        actualizarDatos();
    }//GEN-LAST:event_hoyRadioActionPerformed

    private void atrasadosRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasadosRadioActionPerformed
        // TODO add your handling code here:
        isHoy = !atrasadosRadio.isSelected();
        actualizarDatos();
    }//GEN-LAST:event_atrasadosRadioActionPerformed
    
    public void actualizarDatos() {
        pedidos.clear();
        if(isRegistrar) {
            this.pedidos = control.getOrderByArrivalDate(control.getDate(), isHoy);
            setTableArrival();
        }else {
            //Obtener listado de productos que ya estan en tienda
            setTableOrdersByStore();
        }
    }
    
    /**
     * Metodo para actualizar tabla de pedidos generales
     */
    private void setTableArrival() {
        listPedidos = new String[pedidos.size()][6];

        for(int i=0; i<pedidos.size(); i++) {
            listPedidos[i][0] = pedidos.get(i).getNitCliente();
            listPedidos[i][1] = String.valueOf(pedidos.get(i).getFechaPedido());
            listPedidos[i][2] = String.valueOf(pedidos.get(i).getTotalPedido());
            listPedidos[i][3] = pedidos.get(i).getTiendaOrigen();
            listPedidos[i][4] = pedidos.get(i).getTiendaDestino();
            listPedidos[i][5] = String.valueOf(pedidos.get(i).getArrivalDate());
        }
        pedidosTable.setPreferredSize(new java.awt.Dimension(700, 36*pedidos.size()));
        pedidosTable.setModel(new javax.swing.table.DefaultTableModel(
            listPedidos,
            new String [] {
                "Cliente", "FechaP", "Total", "Origen", "Destino", "Fecha Estimada"
            }
        ));
    }
    
    private void setTableOrdersByStore() {
        listPedidos = new String[pedidos.size()][7];

        for(int i=0; i<pedidos.size(); i++) {
            listPedidos[i][0] = pedidos.get(i).getNitCliente();
            listPedidos[i][1] = String.valueOf(pedidos.get(i).getFechaPedido());
            listPedidos[i][2] = String.valueOf(pedidos.get(i).getAnticipo());
            listPedidos[i][3] = String.valueOf(pedidos.get(i).getTotalPedido());
            listPedidos[i][4] = pedidos.get(i).getTiendaOrigen();
            listPedidos[i][5] = String.valueOf(pedidos.get(i).getFechaLlegada());
            listPedidos[i][6] = String.valueOf(pedidos.get(i).isaTiempo());
        }
        pedidosTable.setPreferredSize(new java.awt.Dimension(700, 36*pedidos.size()));
        pedidosTable.setModel(new javax.swing.table.DefaultTableModel(
            listPedidos,
            new String [] {
                "Cliente", "FechaP", "Anticipo", "Total", "Origen", "Fecha LLegada", "Atrasado"
            }
        ));    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JRadioButton atrasadosRadio;
    private javax.swing.JButton editarButton;
    private javax.swing.JRadioButton hoyRadio;
    private javax.swing.JTable pedidosTable;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JScrollPane scrollTiendas;
    private javax.swing.JLabel sucursalesLabel;
    private javax.swing.JComboBox<String> tipoPedidosCombo;
    // End of variables declaration//GEN-END:variables
}
