package com.intelaf.view;

import com.intelaf.controller.MainControl;
import com.intelaf.model.*;
import java.util.*;

/**
 *
 * @author cesar31
 */
public class TiendasClienteView extends javax.swing.JPanel {

    private MainControl control;
    private Cliente cliente;
    private List<Tienda> tiendas;
    private List<Producto> productos;
    private String[][] lista;

    /**
     * Creates new form VentaView
     */
    public TiendasClienteView() {
        initComponents();
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productosTable = new javax.swing.JTable();
        descriptionLabel = new javax.swing.JLabel();
        productosTiendaLabel = new javax.swing.JLabel();
        tiendasCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(248, 147, 31));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 402));

        productosTable.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productosTable.setEditingColumn(0);
        productosTable.setEditingRow(0);
        productosTable.setMinimumSize(new java.awt.Dimension(600, 250));
        productosTable.setPreferredSize(new java.awt.Dimension(700, 250));
        productosTable.setRowHeight(36);
        productosTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        productosTable.setSelectionForeground(new java.awt.Color(248, 147, 31));
        productosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productosTable);
        productosTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        descriptionLabel.setBackground(new java.awt.Color(248, 147, 31));
        descriptionLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionLabel.setText("Descripción:");
        descriptionLabel.setMinimumSize(new java.awt.Dimension(700, 60));
        descriptionLabel.setPreferredSize(new java.awt.Dimension(700, 80));

        productosTiendaLabel.setBackground(new java.awt.Color(248, 147, 31));
        productosTiendaLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        productosTiendaLabel.setForeground(new java.awt.Color(255, 255, 255));
        productosTiendaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productosTiendaLabel.setText("Productos");
        productosTiendaLabel.setMaximumSize(new java.awt.Dimension(150, 36));
        productosTiendaLabel.setMinimumSize(new java.awt.Dimension(150, 36));
        productosTiendaLabel.setPreferredSize(new java.awt.Dimension(150, 36));

        tiendasCombo.setBackground(new java.awt.Color(0, 0, 0));
        tiendasCombo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tiendasCombo.setForeground(new java.awt.Color(248, 147, 31));
        tiendasCombo.setMinimumSize(new java.awt.Dimension(150, 32));
        tiendasCombo.setPreferredSize(new java.awt.Dimension(150, 32));
        tiendasCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tiendasComboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productosTiendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiendasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productosTiendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiendasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para agregar imagenes e inicializar las variables a utilizar
     */
    private void setComponents() {
        productos = new ArrayList<>();
    }

    /**
     * Metodo para inicializar componentes necesarios para mostrar informacion
     * de las tiendas de donde se hacen pedidos
     *
     * @param control
     * @param cliente
     */
    public void initializeComponents(MainControl control, Cliente cliente) {
        this.control = control;
        this.cliente = cliente;
        this.tiendasCombo.setVisible(true);
        this.tiendas = this.control.getTiendas();
        if (!tiendas.isEmpty()) {
            tiendas.forEach((t) -> {
                tiendasCombo.addItem(t.getCodigo());
            });
        }
        actualizarDatos();
    }

    /**
     * Evento al hacer click sobre la tabla de productos Muestra la descripcion
     * del producto
     *
     * @param evt
     */
    private void productosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosTableMouseClicked
        // TODO add your handling code here:
        int row = productosTable.getSelectedRow();
        if (row != -1) {
            descriptionLabel.setText(productos.get(row).getDescripcion());
        }
    }//GEN-LAST:event_productosTableMouseClicked

    private void tiendasComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tiendasComboItemStateChanged
        // TODO add your handling code here:
        actualizarDatos();
    }//GEN-LAST:event_tiendasComboItemStateChanged

    private void actualizarDatos() {
        //Limpiar listas
        productos.clear();

        //Obtener productos de la base de datos
        if (!tiendas.isEmpty()) {
            String codigo = tiendasCombo.getSelectedItem().toString();
            productos = this.control.getProductosTienda(codigo);
        }

        //Actualizar tablas
        setTableProductos();
    }

    /**
     * Metodo para agregar los productos de la tienda traidos de la base de
     * datos a la tabla
     */
    private void setTableProductos() {
        lista = new String[productos.size()][6];
        for (int i = 0; i < productos.size(); i++) {
            lista[i][0] = productos.get(i).getCodigoProductos();
            lista[i][1] = productos.get(i).getNombre();
            lista[i][2] = productos.get(i).getFabricante();
            lista[i][3] = "Q. " + productos.get(i).getPrecio() + "";
            lista[i][4] = productos.get(i).getGarantia() + "";
            lista[i][5] = productos.get(i).getStock() + "";
        }
        productosTable.setPreferredSize(new java.awt.Dimension(550, 36 * productos.size()));
        productosTable.setModel(new javax.swing.table.DefaultTableModel(
                lista,
                new String[]{
                    "Codigo", "Nombre", "Fabricante", "Precio", "Garantia", "Existencias"
                }
        ));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productosTable;
    private javax.swing.JLabel productosTiendaLabel;
    private javax.swing.JComboBox<String> tiendasCombo;
    // End of variables declaration//GEN-END:variables
}
