
package com.intelaf.view;

import com.intelaf.controller.MainControl;
import com.intelaf.model.*;

/**
 *
 * @author cesar31
 */
public class UsuarioForModal extends javax.swing.JPanel {

    private MainControl control;
    private boolean isEmpleado;
    private boolean isEdit;
    private Empleado empleado;
    private Cliente cliente;
    
    /**
     * Creates new form createCliente
     */
    public UsuarioForModal() {
        initComponents();
    }
    
    public void initializeControl(MainControl control, boolean isEmpleado) {
        this.control = control;
        this.isEmpleado = isEmpleado;
        setComponents();
    }
    
    private void setComponents() {
        isEdit = false;
        if(isEmpleado) {
            informacionLabel.setText("Informacion del Empleado");
            codigoLabel.setText("Codigo*");
            nombreLabel.setText("Nombre*");
            telefonoLabel.setText("Telefono*");
            dpiLabel.setText(("DPI*"));
            emailLabel.setText("Email*");
            direccionLabel.setText("Direccion*");
            creditoLabel.setText("Nit");
            creditoText.setText("");
            creditoText.setEditable(true);
        }
    }
    
    public void initializeEmpleado(Empleado empleado) {
        this.empleado = empleado;
        setEditar();
    }
    
    public void initializeCliente(Cliente cliente) {
        this.cliente = cliente;
        setEditar();
    }
    
    private void setEditar() {
        isEdit = true;
        codigoText.setEditable(false);
        setDatos();
    }
        
    private void setDatos() {
        Persona persona = null;
        String codigo = null;
        double credito = 0;
        if(isEmpleado) {
            if(this.empleado != null) {
                codigo = this.empleado.getCodigo();
                persona = this.empleado;
            }
        } else {
            if(this.cliente != null) {
                credito = this.cliente.getCreditoCompra();
                persona = this.cliente;
            }
        }
        
        if(persona != null) {
            codigoText.setText(isEmpleado ? codigo : persona.getNit());
            nombreText.setText(persona.getNombre());
            telefonoText.setText(persona.getTelefono());
            dpiText.setText((persona.getDpi() != null) ? persona.getDpi() : "");
            emailText.setText((persona.getEmail() != null) ? persona.getEmail() : "");
            direccionText.setText((persona.getDireccion() != null) ? persona.getDireccion() : "");
            creditoText.setText(isEmpleado ? persona.getNit() : "Q. " + credito);
        }else {
            nombreText.setText("");
            telefonoText.setText("");
            dpiText.setText("");
            emailText.setText("");
            direccionText.setText("");
            creditoText.setText(isEmpleado ? "" : "Q. 0.00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionLabel = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        telefonoLabel = new javax.swing.JLabel();
        telefonoText = new javax.swing.JTextField();
        dpiLabel = new javax.swing.JLabel();
        dpiText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        direccionLabel = new javax.swing.JLabel();
        direccionText = new javax.swing.JTextField();
        creditoLabel = new javax.swing.JLabel();
        creditoText = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 147, 31));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));

        informacionLabel.setBackground(new java.awt.Color(248, 147, 31));
        informacionLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        informacionLabel.setForeground(new java.awt.Color(0, 0, 0));
        informacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informacionLabel.setText("Informacion del Cliente");
        informacionLabel.setToolTipText("");
        informacionLabel.setMaximumSize(new java.awt.Dimension(350, 30));
        informacionLabel.setMinimumSize(new java.awt.Dimension(350, 30));
        informacionLabel.setPreferredSize(new java.awt.Dimension(350, 30));

        codigoLabel.setBackground(new java.awt.Color(248, 147, 31));
        codigoLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        codigoLabel.setForeground(new java.awt.Color(0, 0, 0));
        codigoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigoLabel.setText("NIT");
        codigoLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        codigoLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        codigoLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        codigoText.setBackground(new java.awt.Color(255, 255, 255));
        codigoText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        codigoText.setForeground(new java.awt.Color(0, 0, 0));
        codigoText.setMinimumSize(new java.awt.Dimension(150, 30));
        codigoText.setPreferredSize(new java.awt.Dimension(150, 30));
        codigoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoTextKeyTyped(evt);
            }
        });

        nombreLabel.setBackground(new java.awt.Color(248, 147, 31));
        nombreLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreLabel.setText("Nombre");
        nombreLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        nombreLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        nombreLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        nombreText.setBackground(new java.awt.Color(255, 255, 255));
        nombreText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nombreText.setForeground(new java.awt.Color(0, 0, 0));
        nombreText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombreText.setMinimumSize(new java.awt.Dimension(402, 30));
        nombreText.setPreferredSize(new java.awt.Dimension(402, 30));

        telefonoLabel.setBackground(new java.awt.Color(248, 147, 31));
        telefonoLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        telefonoLabel.setForeground(new java.awt.Color(0, 0, 0));
        telefonoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefonoLabel.setText("Telefono");
        telefonoLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        telefonoLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        telefonoLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        telefonoText.setBackground(new java.awt.Color(255, 255, 255));
        telefonoText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        telefonoText.setForeground(new java.awt.Color(0, 0, 0));
        telefonoText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        telefonoText.setMinimumSize(new java.awt.Dimension(150, 30));
        telefonoText.setPreferredSize(new java.awt.Dimension(150, 30));

        dpiLabel.setBackground(new java.awt.Color(248, 147, 31));
        dpiLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        dpiLabel.setForeground(new java.awt.Color(0, 0, 0));
        dpiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dpiLabel.setText("DPI");
        dpiLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        dpiLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        dpiLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        dpiText.setBackground(new java.awt.Color(255, 255, 255));
        dpiText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dpiText.setForeground(new java.awt.Color(0, 0, 0));
        dpiText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dpiText.setMinimumSize(new java.awt.Dimension(150, 30));
        dpiText.setPreferredSize(new java.awt.Dimension(150, 30));

        emailLabel.setBackground(new java.awt.Color(248, 147, 31));
        emailLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("Email");
        emailLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        emailLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        emailLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        emailText.setBackground(new java.awt.Color(255, 255, 255));
        emailText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        emailText.setForeground(new java.awt.Color(0, 0, 0));
        emailText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailText.setMinimumSize(new java.awt.Dimension(402, 30));
        emailText.setPreferredSize(new java.awt.Dimension(402, 30));

        direccionLabel.setBackground(new java.awt.Color(248, 147, 31));
        direccionLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        direccionLabel.setForeground(new java.awt.Color(0, 0, 0));
        direccionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        direccionLabel.setText("Direccion");
        direccionLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        direccionLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        direccionLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        direccionText.setBackground(new java.awt.Color(255, 255, 255));
        direccionText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        direccionText.setForeground(new java.awt.Color(0, 0, 0));
        direccionText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        direccionText.setMinimumSize(new java.awt.Dimension(402, 30));
        direccionText.setPreferredSize(new java.awt.Dimension(402, 30));

        creditoLabel.setBackground(new java.awt.Color(248, 147, 31));
        creditoLabel.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        creditoLabel.setForeground(new java.awt.Color(0, 0, 0));
        creditoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        creditoLabel.setText("Credito");
        creditoLabel.setMaximumSize(new java.awt.Dimension(90, 24));
        creditoLabel.setMinimumSize(new java.awt.Dimension(90, 24));
        creditoLabel.setPreferredSize(new java.awt.Dimension(90, 24));

        creditoText.setEditable(false);
        creditoText.setBackground(new java.awt.Color(255, 255, 255));
        creditoText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        creditoText.setForeground(new java.awt.Color(0, 0, 0));
        creditoText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        creditoText.setText("Q. 0.00");
        creditoText.setMinimumSize(new java.awt.Dimension(150, 30));
        creditoText.setPreferredSize(new java.awt.Dimension(150, 30));

        aceptarButton.setBackground(new java.awt.Color(0, 0, 0));
        aceptarButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        aceptarButton.setForeground(new java.awt.Color(248, 147, 31));
        aceptarButton.setText("Aceptar");
        aceptarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 117, 12)));
        aceptarButton.setMinimumSize(new java.awt.Dimension(125, 32));
        aceptarButton.setPreferredSize(new java.awt.Dimension(125, 32));
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelarButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(248, 147, 31));
        cancelarButton.setText("Cancelar");
        cancelarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 117, 12)));
        cancelarButton.setMinimumSize(new java.awt.Dimension(125, 32));
        cancelarButton.setPreferredSize(new java.awt.Dimension(125, 32));
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombreText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dpiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dpiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(direccionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(creditoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(41, 41, 41)
                            .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(informacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para verificar la informacion del ciente antes de procesar la venta
     * @param evt 
     */
    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
        String id = codigoText.getText();
        String nombre = nombreText.getText();
        String telefono = telefonoText.getText();
        String dpi = dpiText.getText();
        String email = emailText.getText();
        String direccion = direccionText.getText();
        String nitOrCredito = creditoText.getText();
        
        if(isEmpleado) {
            if(!id.isEmpty() && !nombre.isEmpty() && !telefono.isEmpty() && !dpi.isEmpty() && !email.isEmpty() && !direccion.isEmpty()) {
                if(isEdit) {
                    empleado.setNombre(nombre);
                    empleado.setTelefono(telefono);
                    empleado.setDpi(dpi);
                    empleado.setEmail(email);
                    empleado.setDireccion(direccion);
                    
                    empleado.setNit(!nitOrCredito.isEmpty() ? nitOrCredito : null);
                    
                    control.setUpdateEmpleado(empleado);
                } else {
                    if(empleado == null) {
                        //Code for new user
                        Empleado tmp =new Empleado(nombre, id, telefono, dpi);
                        tmp.setEmail(email);
                        tmp.setDireccion(direccion);
                        tmp.setNit(!nitOrCredito.isEmpty() ? nitOrCredito : null);

                        control.setEmpleado(tmp);
                    } else {
                        control.crearAlerta("Error", "Ya existe un empleado con ese codigo", null);
                    }
                }
            } else {
                control.crearAlerta("Error", "Debe de llenar todos los campos obligatorios(*)", null);
            }
        } else {
            if(!id.isEmpty() && !nombre.isEmpty() && !telefono.isEmpty()) {
                if(isEdit) {
                    cliente.setNombre(nombre);
                    cliente.setTelefono(telefono);
                    cliente.setDpi(!dpi.isEmpty() ? dpi : null);
                    cliente.setEmail(!email.isEmpty() ? email : null);
                    cliente.setDireccion(!direccion.isEmpty() ? direccion : null);
                    
                    control.setUpdateCliente(cliente);
                } else {
                    if(cliente == null) {
                        //Code for new client
                        Cliente tmp = new Cliente(nombre, telefono, 0);
                        tmp.setNit(id);
                        tmp.setDpi(!dpi.isEmpty() ? dpi : null);
                        tmp.setEmail(!email.isEmpty() ? email : null);
                        tmp.setDireccion(!direccion.isEmpty() ? direccion : null);

                        control.setCliente(tmp);
                    } else {
                        control.crearAlerta("Error", "Ya existe un cliente con ese codigo", null);
                    }
                }
            } else {
                control.crearAlerta("Error", "Debe llenar los campos nit, nombre y telefono", null);
            }
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed
    
    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        control.closeModal();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void codigoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyReleased
        // TODO add your handling code here:
        if(!codigoText.getText().isEmpty() && !codigoText.getText().isBlank()){
            if(isEmpleado){
                this.empleado = control.getEmpleado(codigoText.getText());
            }else {
                this.cliente = control.getCliente(codigoText.getText());
            }
        } else {
            if(isEmpleado) {
                this.empleado = null;
            } else {
                this.cliente = null;
            }
        }
        //setDatos();
    }//GEN-LAST:event_codigoTextKeyReleased

    private void codigoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextKeyPressed

    private void codigoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyTyped
        // TODO add your handling code here:
        if(codigoText.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_codigoTextKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoText;
    private javax.swing.JLabel creditoLabel;
    private javax.swing.JTextField creditoText;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField direccionText;
    private javax.swing.JLabel dpiLabel;
    private javax.swing.JTextField dpiText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel informacionLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoText;
    // End of variables declaration//GEN-END:variables
}
