
package com.intelaf.view;

import com.intelaf.controller.MainControl;
import com.intelaf.model.*;
import java.awt.Image;
import java.util.*;
import javax.swing.ImageIcon;

/**
 *
 * @author cesar31
 */
public class VentaView extends javax.swing.JPanel {

    private MainControl control;
    private Tienda tienda;
    private List<Producto> productos;
    private List<Producto> productosCliente;
    private String[][] lista;
    private String[][] listaCliente;
    
    /**
     * Creates new form VentaView
     */
    public VentaView() {
        initComponents();
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productosTable = new javax.swing.JTable();
        descriptionLabel = new javax.swing.JLabel();
        cantidadText = new javax.swing.JTextField();
        cantidadLabel = new javax.swing.JLabel();
        carritoButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 147, 31));
        setMinimumSize(new java.awt.Dimension(800, 700));

        productosTable.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productosTable.setMinimumSize(new java.awt.Dimension(700, 250));
        productosTable.setPreferredSize(new java.awt.Dimension(700, 250));
        productosTable.setRowHeight(36);
        productosTable.setRowMargin(10);
        productosTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        productosTable.setSelectionForeground(new java.awt.Color(248, 147, 31));
        productosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(productosTable);
        productosTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        descriptionLabel.setBackground(new java.awt.Color(248, 147, 31));
        descriptionLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionLabel.setText("Descripción:");
        descriptionLabel.setMinimumSize(new java.awt.Dimension(700, 60));
        descriptionLabel.setPreferredSize(new java.awt.Dimension(700, 80));

        cantidadText.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        cantidadText.setForeground(new java.awt.Color(0, 0, 0));
        cantidadText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadText.setText("Número");
        cantidadText.setToolTipText("");
        cantidadText.setMinimumSize(new java.awt.Dimension(90, 36));
        cantidadText.setPreferredSize(new java.awt.Dimension(90, 36));

        cantidadLabel.setBackground(new java.awt.Color(248, 147, 31));
        cantidadLabel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        cantidadLabel.setForeground(new java.awt.Color(255, 255, 255));
        cantidadLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cantidadLabel.setText("Cantidad");
        cantidadLabel.setMaximumSize(new java.awt.Dimension(90, 36));
        cantidadLabel.setMinimumSize(new java.awt.Dimension(90, 36));
        cantidadLabel.setPreferredSize(new java.awt.Dimension(90, 36));

        carritoButton.setBackground(new java.awt.Color(248, 147, 31));
        carritoButton.setForeground(new java.awt.Color(255, 255, 255));
        carritoButton.setMaximumSize(new java.awt.Dimension(50, 50));
        carritoButton.setMinimumSize(new java.awt.Dimension(50, 50));
        carritoButton.setPreferredSize(new java.awt.Dimension(50, 50));
        carritoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carritoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(carritoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cantidadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(carritoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setComponents() {
        ImageIcon imgCarrito = new ImageIcon(getClass().getResource("/images/carrito.png"));
        carritoButton.setIcon(new ImageIcon(imgCarrito.getImage().getScaledInstance(carritoButton.getPreferredSize().width, carritoButton.getPreferredSize().height, Image.SCALE_SMOOTH)));
    }
    
    private void carritoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carritoButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("carrito");
    }//GEN-LAST:event_carritoButtonActionPerformed

    public void initializeComponents(MainControl control, Tienda tienda) {
        this.control = control;
        this.tienda = tienda;
        getProductos();
    }
    
    private void getProductos() {
        productos = control.getProductosTienda(tienda.getCodigo());
        listaCliente = new String[productos.size()][6];
        
        lista = new String[productos.size()][6];
        for (int i = 0; i < productos.size(); i++) {
            lista[i][0] = productos.get(i).getCodigoProductos();
            lista[i][1] = productos.get(i).getNombre();
            lista[i][2] = productos.get(i).getFabricante();
            lista[i][3] = "Q. " + productos.get(i).getPrecio() + "";
            lista[i][4] = productos.get(i).getGarantia()+ "";
            lista[i][5] = productos.get(i).getStock()+ "";
            listaCliente[i][0] = productos.get(i).getCodigoTienda();
        }
        
        productosTable.setModel(new javax.swing.table.DefaultTableModel(
            lista,
            new String [] {
                "Codigo", "Nombre", "Fabricante", "Precio", "Garantia", "Existencias"
            }
        ));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JTextField cantidadText;
    private javax.swing.JButton carritoButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productosTable;
    // End of variables declaration//GEN-END:variables
}
